openapi: 3.0.0
info:
  version: "1.4.2"
  title: Event Scheduling for Generic Partner Integrations
  description: Scheduling information directly from the EMR.
  x-logo:
    url: https://docspera.com/assets/D3/pic/Logo-Full-White-Padded.png
    backgroundColor: "#0096FA"
    href: https://docspera.com
  contact:
    email: jon@docspera.com
  license:
    name: Proprietary
tags:
  - name: user
    x-displayName: "Authenticated User"
    description: |
      apis available to an authenticated user
security:
  - UserSecurity: []
paths:
  /event-scheduling:
    post:
      description: Ships all the necessary scheduling information.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventScheduling"
      responses:
        "200":
          description: Successfully accepted a new case
          content:
            "*/*":
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
        "400":
          $ref: "#/components/responses/400Error"
    get:
      description: Returns details of an event.
      parameters:
        - in: query
          name: event_id
          description: DocSpera identifier of the event
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Event details
          $ref: "#/components/schemas/EventScheduling"
        "400":
          $ref: "#/components/responses/400Error"
servers:
  - url: https://virtserver.swaggerhub.com/DocSpera/Event_Scheduling_Generic/1.0.0
components:
  parameters:
    PageLimit:
      name: limit
      in: query
      description: Limits the number of items on a page
      schema:
        type: integer
    PageNumber:
      name: offset
      in: query
      description: Specifies the page number of the artists to be displayed
      schema:
        type: integer
  responses:
    400Error:
      description: Invalid request
      content:
        "*/*":
          schema:
            type: object
            properties:
              status:
                type: string
                example: Error
  securitySchemes:
    UserSecurity:
      type: http
      scheme: basic
  schemas:
    EventScheduling:
      type: object
      required:
        - username
      properties:
        event:
          type: object
          properties:
            event_id:
              type: integer
              example: 199967
              description: Calendar event ID.
            universal_id:
              type: string
              example: "26B21A"
              description: Universal ID.
            start:
              type: string
              example: "2015-05-27T14:00:00Z"
              description: ISO date of when the event will start in UTC
            end:
              type: string
              example: "2015-05-27T16:30:00Z"
              description: ISO date of when the event will end in UTC
            case:
              type: string
              example: "Total Hip Replacement"
              description: Name of the event.
            procedure:
              type: string
              example: Hip
              description: The type of appointment
            orientation:
              type: integer
              example: Left
              description: "Left, Right, Unknown"
            details:
              type: string
              example: Request for addtional femoral head
              description: Free form text field coming from the EMR that describes the
                procedure
            status:
              type: string
              example: Confirmed
              description: "Possible options: Confirmed, Pending, Cancelled"
            laterality:
              type: string
              example: "Bi-lateral"
              description: "'Bi-lateral', 'Uni-lateral', ''"
            location:
              type: object
              properties:
                ahaid:
                  type: string
                  example: 123
                  description: Facility ID
                name:
                  type: string
                  example: St John Hospital
                  description: Surgical location
            physician:
                type: array
                items:
                  properties:
                    npi:
                      type: string
                      example: "1005300087"
                      description: NPI is a unique 10-digit identification number issued by CMS
                    name:
                      type: string
                      example: Andrew Surgeon
                      description: Full name of attending physician
            reps:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: "430"
                      description: NPI is a unique 10-digit identification number issued by CMS
                    name:
                      type: string
                      example: Brian Miller
                      description: Full name of attending physician
            patient:
              type: object
              properties:
                  mrn:
                    type: string
                    example: 48214XZ3
                    description: Medical record number of the patient
                  initials:
                    type: string
                    example: "B. M."
                    description: Medical record number of the patient
            demographics:
              type: object
              properties:
                gender:
                  type: string
                  example: Female
                  description: "Patient's natural gender. Legal values: * Male, * Female"
                age:
                  type: string
                  example: 53
                  description: Medical record number of the patient
                height:
                  type: string
                  example: "178.00"
                  description: DocSpera medical record number
                weight:
                  type: string
                  example: 71.214
                  description: Date of birth, in ISO format (YYYYMMDD)
            equipment:
              type: object
              properties:
                devices:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                        example: Device A iHip 2000
                        description: Full name of attending physician
            study:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 181002367
                      description: NPI is a unique 10-digit identification number issued by CMS
                    name:
                      type: string
                      example: "MRIX LUMBAR"
                      description: Full name of attending physician
                    url:
                      type: string
                      example: "https://docspera/dicom/4159152/study/181002367/1744f3954c37e2ea6bf693bf37b8e98b.zip"
                      description: Full name of attending physician